fix for svg not rendered properly, when mask is present #1177
canvg/canvg pull request #1183
Opened 2020-08-24 16:38 UTC by AlkaBeniwal

2020-11-06 09:55 UTC, Llorx commented
Why this has not been merged? Seems like a performance improvement as no intermediate canvas is created.

2020-11-06 09:56 UTC, Llorx requested changes
Remove the comment as is making Trvis return an error.

2020-11-06 09:56 UTC, Llorx commented on src/Document/MaskElement.ts
> +        //canvas is getting blurred when mask is present in svg,using target scaled up canvas instead of temporary canvas
Remove this

2020-11-06 10:03 UTC, dangreen commented
@Llorx Hi.

> Why this has not been merged? 

Because this solution fix one case and breaks all others.

2020-11-06 10:15 UTC, Llorx commented
Oh I see @dangreen

2020-11-06 13:39 UTC, AlkaBeniwal commented
> @Llorx Hi.
> 
> > Why this has not been merged?
> 
> Because this solution fix one case and breaks all others.

Hi @dangreen, just wanted to know in what all cases it is breaking so that I can also try out the new fix.

2020-11-06 13:45 UTC, AlkaBeniwal commented on src/Document/MaskElement.ts
> +        //canvas is getting blurred when mask is present in svg,using target scaled up canvas instead of temporary canvas
sure, thanks for reviewing it.

2021-07-12 01:50 UTC, gabelerner commented
@AlkaBeniwal @Llorx closing out of staleness, please reopen against latest master and we'll see if tests pass there

2021-07-12 01:50 UTC, closed without merging